### ISSUE TITLE
Too many visits. Exceeded the API Rate Limit.

### ISSUE THREAD

**Issue by vinayakdev** [zhouaini528/bybit-php#20]
`
Route::get('/bybit', function () {
    $key = env('BYBIT_KEY');
    $secret = env('BYBIT_SECRET');

    $bybit = new \Lin\Bybit\BybitLinear($key, $secret);
    // dd($bybit);

    try {
        $result = $bybit->privates()->getPositionList([
            'symbol' => 'BTCUSDT',
        ]);
        // $result = $bybit->privates()->postOrderCreate([
        //     //'order_link_id'=>'xxxxxxxxxxxxxx',
        //     'side' => 'Buy',
        //     'symbol' => 'BTCUSDT',
        //     'order_type' => 'Limit',
        //     'qty' => '1',
        //     'price' => '49000',
        //     'time_in_force' => 'GoodTillCancel',
        //     'reduce_only' => 'false',
        //     'close_on_trigger' => 'false',
        // ]);

        dump($result);
    } catch (\Exception $e) {
        dd($e->getMessage());
    }

});
`

why am i getting rate limited, is there something wrong with what im doing?

**Comment by zhouaini528** [comment]
> ` Route::get('/bybit', function () { $key = env('BYBIT_KEY'); $secret = env('BYBIT_SECRET');
> 
> ```
> $bybit = new \Lin\Bybit\BybitLinear($key, $secret);
> // dd($bybit);
> 
> try {
>     $result = $bybit->privates()->getPositionList([
>         'symbol' => 'BTCUSDT',
>     ]);
>     // $result = $bybit->privates()->postOrderCreate([
>     //     //'order_link_id'=>'xxxxxxxxxxxxxx',
>     //     'side' => 'Buy',
>     //     'symbol' => 'BTCUSDT',
>     //     'order_type' => 'Limit',
>     //     'qty' => '1',
>     //     'price' => '49000',
>     //     'time_in_force' => 'GoodTillCancel',
>     //     'reduce_only' => 'false',
>     //     'close_on_trigger' => 'false',
>     // ]);
> 
>     dump($result);
> } catch (\Exception $e) {
>     dd($e->getMessage());
> }
> ```
> 
> }); `
> 
> why am i getting rate limited, is there something wrong with what im doing?

Use the V5 API
```php
$bybit=new BybitV5($key,$secret);

//You can set special needs
$bybit->setOptions([
    //Set the request timeout to 60 seconds by default
    'timeout'=>10,

    'headers'=>[
        //X-Referer or Referer
        //X-BAPI-RECV-WINDOW
        //cdn-request-id
        'X-BAPI-RECV-WINDOW'=>'6000',
    ]
]);


try {
    $result=$bybit->order()->postCreate([
        'category'=>'spot',
        'symbol'=>'BTCUSDT',
        'side'=>'buy',
        'orderType'=>'limit',
        'qty'=>'1',
        'price'=>'1000',

        //'orderLinkId'=>'xxxxxxxxxxx',
    ]);
    print_r($result);
}catch (\Exception $e){
    print_r($e->getMessage());
}
```
