### ISSUE TITLE
Proxy with authorization ip:port@login:pass

### ISSUE THREAD

**Issue by artstudia86** [zhouaini528/bybit-php#9]
How to connect private proxies like ip:port@login:pass ?

**Comment by Prooksius** [comment]
$login = '.....';
$password = '.......';
$IP_address = 'XX.XX.XX.XX';
$port = 'XXXX';

$bybit = new BybitLinearRequest();
$bybit->setOptions([
  'proxy' => [
     'http'  => 'http://' . $login . ':' . $password . '@' . $IP_address . ':' . $port,
     'https' => 'http://' . $login . ':' . $password . '@' . $IP_address . ':' . $port,
  ],
]);

$result = $bybit->publics()->getTickers();
